config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get 'homes/about'
  post 'lists' => 'lists#create'
  get 'lists' => 'lists#index'
  get 'lists/:id' => 'lists#show', as: 'list'
  get 'lists/:id/edit' => 'lists#edit', as: 'edit_list'
  patch 'list/:id' => 'lists#update', as: 'update_list'
  delete 'lists/:id' => 'lists#destroy', as: 'destroy_list'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :image
  
  validates :title, presence: true
  validates :body,  presence: true
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to '/homes/top'
    else
      render :new
    end
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to list_path(list.id)
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to '/lists'
  end

  private

  def list_params
    params.require(:list).permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/about.html.slim
h1 ABOUT

app/views/homes/top.html.slim
h1 トップページ
p テキスト

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SampleSlim
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
  body
    = yield

app/views/lists/edit.html.slim
h1 編集画面
= form_with model: @list, url: update_list_path(@list.id), method: :patch do |f|
  h4 タイトル
  = f.text_field :title
  h4 本文
  = f.text_area :body
  h4 画像
  = f.file_field :image, accept: "image/*"
  = f.submit '保存'

app/views/lists/index.html.slim
h1 投稿一覧
- @lists.each do | list |
  p タイトル
  span = link_to list.title,"/lists/#{list.id}"
  

app/views/lists/new.html.slim
h1 新規投稿
= form_with model: @list, url: '/lists',method: :post  do |f|
  h4 タイトル
  = f.text_field :title
  h4 本文
  = f.text_area :body
  h4 画像
  = f.file_field :image, accept: "image/*"
  = f.submit '投稿'

app/views/lists/show.html.slim
h1 投稿詳細
h2 タイトル
p = @list.title
h2 本文
p = @list.body
h2 画像
- if @list.image.attached?
  = image_tag @list.image, size: "300x300"
- else
  = image_tag 'no_image', size: "300x300"
= link_to "編集", edit_list_path(@list.id)
= button_to "削除", destroy_list_path(id: @list.id), data: { turbo_method: :delete }, "data-confirm" => "本当に削除しますか？"